mame: 'Get & Cache  Dependencies'
description: 'Ger the dependensies (via npm) and cache them.'
inputs:
  caching:
    description: 'Whether to cache deprndencies or not'
runs: 
  using: 'composite'
  steps: 
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true' && inputs.caching != 'true'
      run: npm ci
      shell: bash