name: Test Deploy
on: push
jobs: 
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
       
      - name: install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Run tests
        run: npm test
      
      - name: Run buils
        run: npm run build
      - name: Deploy code
        run: echo "Deploying..."

